spring:
  application:
    name: hometown
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hometown_db
    username: root
    password: 1234

#配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  #??mapper文件存放路径
  mapper-locations: classpath:com/mjc/mapper/*.xml

#????????
web:
  upload-path: D:/Code/image  # ??????????????
  image-max-size: 5MB      # ??????
  allowed-image-types: image/jpeg,image/png,image/gif,image/bmp  # ???????

