#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hometown_db
    #url: jdbc:mysql://192.168.100.128:3306/hometown_db #虚拟机数据库
    #url: jdbc:mysql://192.168.100.128:3307/hometown_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai      虚拟机数据库地址 docker
    username: root
    #username: hometown
    password: 1234
    #password: hometown
    #password: 123   虚拟机数据库密码 docker
  data:
    redis:
      #host: 127.0.0.1
      #host: 192.168.100.128
      host: localhost
      port: 6379
      password: 123456
      #password: hometown  #服务器密码
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 6
