server:
  port: 8080
spring:
  application:
    name: hometown
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hometown_db
    #url: jdbc:mysql://192.168.100.128:3306/hometown_db #虚拟机数据库
    #url: jdbc:mysql://192.168.100.128:3307/hometown_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai      虚拟机数据库地址 docker
    username: root
    password: 1234
    #password: 123   虚拟机数据库密码 docker
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 6
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

#配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  #??mapper文件存放路径
  mapper-locations: classpath:com/mjc/mapper/*.xml

#????????
web:
  upload-path: D:/Code/image  # ??????????????
  image-max-size: 5MB      # ??????
  allowed-image-types: image/jpeg,image/png,image/gif,image/bmp  # ???????

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mjc.controller

hometown:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: mjcshuai
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

# 图形化验证码
kaptcha:
  border: "yes"
  border-color: "105,179,90"
  text-producer-font-color: "blue"
  image-width: "160"
  image-height: "60"
  text-producer-font-size: "35"
  session-key: "kaptchaCodeMath"
  text-producer-impl: "com.mjc.common.KaptchaTextCreator"
  noise-impl: "com.google.code.kaptcha.impl.NoNoise"


