server:
  port: 8080
spring:
  application:
    name: hometown
  profiles:
    active: dev # 激活dev环境配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jackson:
  default-property-inclusion: non_null # JSON处理时忽略非空字段

#配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  #??mapper文件存放路径
  mapper-locations: classpath:com/mjc/mapper/*.xml

#????????
web:
  upload-path: D:/Code/image  # ??????????????
  image-max-size: 5MB      # ??????
  allowed-image-types: image/jpeg,image/png,image/gif,image/bmp  # ???????

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mjc.controller

hometown:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: mjcshuai
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  # 自定义文件配置
  file:
    # 图片存储的硬盘绝对路径 (注意 Windows 路径格式)
    upload-path: D:/Code/Hometown/images/
    # 前端访问的 URL 前缀，比如 http://localhost:8080/images/xxx.jpg
    access-path: /images/


# 图形化验证码
kaptcha:
  border: "yes"
  border-color: "105,179,90"
  text-producer-font-color: "blue"
  image-width: "160"
  image-height: "60"
  text-producer-font-size: "35"
  session-key: "kaptchaCodeMath"
  text-producer-impl: "com.mjc.common.KaptchaTextCreator"
  noise-impl: "com.google.code.kaptcha.impl.NoNoise"

