spring:
  application:
    name: hometown
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hometown_db
    #url: jdbc:mysql://192.168.100.128:3307/hometown_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai      虚拟机数据库地址 docker
    username: root
    password: 1234
    #password: 123   虚拟机数据库密码 docker

#配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  #??mapper文件存放路径
  mapper-locations: classpath:com/mjc/mapper/*.xml

#????????
web:
  upload-path: D:/Code/image  # ??????????????
  image-max-size: 5MB      # ??????
  allowed-image-types: image/jpeg,image/png,image/gif,image/bmp  # ???????

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mjc.controller

