spring:
  application:
    name: hometown

  #?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hometown_db
    username: root
    password: 1234

#??mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????????
    map-underscore-to-camel-case: true
  #??mybatis??
  mapper-locations: classpath:com/mjc/mapper/*.xml